### ISSUE TITLE
5-fold cross validation

### ISSUE THREAD

**Issue by lgalmant** [google/speaker-id#1]
Hello,
I would like to get the exact 5-fold cross validation performed on NIST_SRE2000, disk 8, used in https://arxiv.org/pdf/1810.04719.pdf

Thanks.

**Comment by wq2012** [comment]
I don't think we kept a record of that. My impression is that the 5 folds were generated randomly, each with the same size.

You could send an email to Aonan Zhang <szyagn@gmail.com> to check if he still has the record.
