### ISSUE TITLE
Speaker Verification

### ISSUE THREAD

**Issue by erdeme36** [google/speaker-id#18]
Hi, I want to create a speaker verification flow in Dialogflow CX but I couldn't find the prebuilt flows like in this video. If you can inform me, I would be pleased. I really appreciate any help you can provide. https://www.youtube.com/watch?time_continue=82&v=uKyercLi1C8&feature=emb_logo

**Comment by wq2012** [comment]
Thanks for your question.

For this, you need to talk to your GCP seller. You can find information at this page: https://cloud.google.com/contact

**Comment by nk-gears** [comment]
> Hi, I want to create a speaker verification flow in Dialogflow CX but I couldn't find the prebuilt flows like in this video. If you can inform me, I would be pleased. I really appreciate any help you can provide. https://www.youtube.com/watch?time_continue=82&v=uKyercLi1C8&feature=emb_logo

Did you figured out how to integrate?. Could you please share your findings ?
