### ISSUE TITLE
ref_text isn't split in a consistent manner in `get_aligned_hyp_speakers`

### ISSUE THREAD

**Issue by kamilakesbi** [google/speaker-id#35]
## Explanation of the issue: 

In `get_aligned_hyp_speakers`, `ref_text` isn't split in a consistent manner: 

- In `levenshtein.levenshtein_with_edits`,  the text is split using the delimiter (" "): 

https://github.com/google/speaker-id/blob/8cc5c5181b863b6fd00e2d183cdf207fed8c864f/DiarizationLM/diarizationlm/levenshtein.py#L27

- While in `get_aligned_hyp_speakers`, text is split without delimiter: 

https://github.com/google/speaker-id/blob/8cc5c5181b863b6fd00e2d183cdf207fed8c864f/DiarizationLM/diarizationlm/utils.py#L85

## Min reproducer: 

This can cause an error in some cases. Here's a min reproducer: 

```
from diarizationlm.utils import get_aligned_hyp_speakers

src_text = "This is  an example  text."
tgt_text = "This is  an other example text "
src_spk = '1 1 1 1 1'

tgt_spk_align = get_aligned_hyp_speakers(
      hyp_text=tgt_text,
      ref_text=src_text,
      ref_spk=src_spk,
  )
```
which gives the error: 

```
Traceback (most recent call last):
  File "/home/user/app/DiarizersLM/min_reproducer.py", line 9, in <module>
    tgt_spk_align = get_aligned_hyp_speakers(
  File "/home/user/app/env/lib/python3.9/site-packages/diarizationlm/utils.py", line 94, in get_aligned_hyp_speakers
    hyp_spk_align.append(ref_spk_list[i])
IndexError: list index out of range
```

## Solution: 

A potential solution would be to simply remove the delimiter in the `levenshtein_with_edits` method and simply use `.split()`. 

I can open a PR for this.

**Comment by wq2012** [comment]
Thanks! This is indeed a bug!

`levenshtein` is my personal rewrite of Google's internal C++ implementation, which uses `absl::StrSplit()`.

However `absl::StrSplit()` removes any empty results, but in Python `str.split(" ")` does not do that.
