### ISSUE TITLE
Question about the cpWER metric

### ISSUE THREAD

**Issue by LyuLumos** [google/speaker-id#37]
Hi, I have some questions about the metrics. cpWER is the minimum value of {WER(all_permute_hyp_transcript, ref)}, then cpWER should be less than or equal to WER. For example, cpWER of `spk1: x, spk2: y` and `spk2: y, spk1: x` should be zero.

However in the paper and in the results of my test, cpWER sometimes is higher than WER, why is that?

Minimum Reproducible Example
```py
import diarizationlm

json_dict = {
  "utterances": [
      {
          "utterance_id": "utt2",
          "hyp_text": "d e f",
          "hyp_spk":  "1 1 1",
          "ref_text": "e f",
          "ref_spk":  "1 2",
      },
  ]
}
result = diarizationlm.compute_metrics_on_json_dict(json_dict)
print("WER =", result["WER"])
print("WDER =", result["WDER"])
print("cpWER =", result["cpWER"])

# WER = 0.5
# WDER = 0.5
# cpWER = 2.0
```
 I noticed that the author used
```
# https://github.com/google/speaker-id/blob/master/DiarizationLM/diarizationlm/metrics.py
# line 175
# Solve alignment.
  row_index, col_index = optimize.linear_sum_assignment(
      cost_matrix, maximize=True
  )
```
 may I ask why it was implemented this way? And why is cpWER higher than WER?
 
 Thanks for the answer, and for the author's contribution!

**Comment by wq2012** [comment]
No, cpWER is always equal to or larger than WER. They are only equal when you have perfect speaker diarization.

Permutation means the permutation of speakers, not the words.
