### ISSUE TITLE
No module word_levenshtein

### ISSUE THREAD

**Issue by Christofferelo** [google/speaker-id#38]
Hello
I get `ModuleNotFoundError: No module named 'word_levenshtein'` from installing `diarizationlm` through pip and running the script from this example under [_Usage_](https://huggingface.co/google/DiarizationLM-8b-Fisher-v2).

I suspect that you in your `requirements.txt` may need to use `word-levenshtein` instead of `word_levenshtein`

**Comment by wq2012** [comment]
Thanks. This is very weird because `word_levenshtein` had been always working for me, and also working well for github actions.
