### ISSUE TITLE
Data preparation for the Fisher Corpus and CallHome American English Speech datasets used in the DiarizationLM paper

### ISSUE THREAD

**Issue by Maxwell-LMC** [google/speaker-id#40]
I am interested in doing further research the DiarizationLM paper using the same datasets. However, I noticed that both the Fisher Corpus and CallHome American English dataset are recorded in 2-channel u-law format. Upon reading the diarizationLM paper and the other papers that were cited by your team, I was not able to find a clear instruction on how the team processed the stereo audio files to feed into the ASR and diarization modules. 

The reason behind my inquiry is, the DiarizationLM paper only used conversations that contain 2 speakers, and since they are telephone data, one speaker is entirely in one channel and the other speaker in the other channel. This potentially makes the diarization task much easier. The usual practice is to merge the stereo audio file into a mono-channel file, as briefly mentioned in [Speaker Diarization with LSTM](https://arxiv.org/pdf/1710.10468) and [Developing On-Line Speaker Diarization](https://www.isca-archive.org/interspeech_2017/dimitriadis17_interspeech.pdf). I wonder what kind of pre-processing took place before summing the two channels, if any.

I highly appreciate the effort put into the DiarizationLM paper, and I really hope that I could contribute more on top of the existing results!

**Comment by wq2012** [comment]
Thanks for reaching out.

I don't exactly recall the specs all of the datasets we use.

But in our data preparation pipeline, if an audio has more than one channel, we simply take the mean value from all channels as the ultimate mono channel sample.

**Comment by Maxwell-LMC** [comment]
Thank you for your quick reply! That really helped, thank you so much!

**Comment by Maxwell-LMC** [comment]
Sorry to bother you again! I would like to ask was there any echo cancellation performed on the dataset if it is 2-channel telephone audio data (before taking the mean value)? Because there might be some artefacts caused by echoes in those old telephone recordings.

Thank you for your quick reply once again!

**Comment by wq2012** [comment]
No. We don't do anything other than simply averaging all channels.

**Comment by Maxwell-LMC** [comment]
Thank you for the quick reply again! It helps a lot!
